site_name: "gestalt"

theme:
  name: "material"

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        import:
        - https://installer.readthedocs.io/en/stable/objects.inv

watch:
- gestalt
- docs